name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# jobs:
#   build-linux:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v2
#     - name: configure
#       run: ./ecSource/scripts/configure.sh
#       shell: bash
#     - name: cmake build and run
#       run: ./ecSource/scripts/run.sh
#       shell: bash
  
#   build-osx:

#     runs-on: macos-latest

#     steps:
#     - uses: actions/checkout@v2
#     - name: configure
#       run: ./ecSource/scripts/configure.sh
#       shell: bash
#     - name: cmake build and run
#       run: ./ecSource/scripts/run.sh
#       shell: bash
      
#   build-windows:

#     runs-on: windows-latest

#     steps:
#     - uses: actions/checkout@v2
#     - name: configure
#       run: ./ecSource/scripts/configure.sh
#       shell: bash
#     - name: make
#       run: ./ecSource/scripts/run.sh
#       shell: bash
